image: node:16 # Using Node.js version 16

stages:
  - build
  - deploy

build:
  tags:
    - docker
  stage: build
  script:
    - npx pnpm install # Install dependencies using npx
    - npx pnpm run build # Build the website
  artifacts:
    paths:
      - public

pages:
  tags:
    - docker
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
