image: node:latest

stages:
  - build
  - deploy

build:
  tags:
    - docker
  stage: build
  script:
    - npm install -g pnpm # Install pnpm
    - pnpm install # Install dependencies
    - pnpm run build # Build the website
  artifacts:
    paths:
      - public

pages:
  tags:
    - docker
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
